<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">USUARIOS</h4></div>
    </div>
    <form class="form-inline form-group">                    
        <label>Filtrar por: </label>
        <div class="btn-group">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="sel" type="button"><h7>Seleccione...</h7><span class="caret"></span></button>
            <ul class="dropdown-menu sel" role="menu">
                <li><a href='#'>Usuario</a></li>
                <li><a href='#'>Perfil</a></li>
                <li><a href='#'>Estado</a></li>
                <li><a href='#'>Cedula</a></li>
            </ul>
        </div>
        <div class="form-group">
        <input type="text" name="usuario" class="form-control" >
        </div>
    </form>
    <div style="text-align: right" class="form-group">
        <button type="button" class="btn btn-danger" name="other">Añadir otro filtro</button>
        <input type="button" value="Buscar" class="btn btn-danger"/>
    </div>
    <div style="background: white; padding: 5px; border-radius: 5px; border: 1px #ccc solid; box-shadow: 1px 0px 5px 1px #cccccc;">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Cuenta</th>
                    <th class="text-center">Usuario</th>
                    <th class="text-center">Cargo</th>
                    <th class="text-center">Perfil</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Identificación</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->datos as $d) : ?>
                <tr>
                    <td><?php echo $d->nombre_usuario; ?></td>
                    <td><?php echo $d->nombre_real . " " . $d->apellido_real; ?></td>
                    <td><?php echo $this->escape($d->cargo); ?></td>
                    <td><?php echo $this->escape($d->perfil); ?></td>
                    <td><?php echo $this->escape($d->estado); ?></td>
                    <td><?php echo $this->escape($d->identificacion); ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                              Opciones <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu" role="menu">
                              <li><a href="#">Editar</a></li>
                              <li><a href="#">Eliminar</a></li>
                              <li><a href="#">Actualizar</a></li>
                              <li class="divider"></li>
                              <li><a href="#">Acción #4</a></li>
                            </ul>
                          </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div align="right">
        <a class="btn btn-danger" href="<?php echo $this->url(array('module'=>'default','controller'=>'usuarios','action'=>'insertar')); ?>">Ingresar nuevo usuario</a>
        </div>
        
        <p class="text-center">
    <button class="btn btn-default" data-toggle="modal" data-target="#loginModal">Login</button>
</p>

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Login</h4>
            </div>

            <div class="modal-body">
                <!-- The form is placed inside the body of modal -->
                <form id="loginForm" method="post" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-xs-3 control-label">Username</label>
                        <div class="col-xs-5">
                            <input type="text" class="form-control" name="username" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label">Password</label>
                        <div class="col-xs-5">
                            <input type="password" class="form-control" name="password" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-5 col-xs-offset-3">
                            <button type="submit" class="btn btn-primary">Login</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('.dropdown-toggle').dropdown();
         $(function(){

    $(".sel").on('click', 'li a', function(){
      $("[id=sel] > h7").text($(this).text());
      $("[id=sel]").val($(this).text());
   });

});
    });
</script>
    </div>
    
</aside>
