<aside style="width: 60%;">
    
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">USUARIOS</h4></div>
    </div>
    <form class="well form-inline">                    
        Usuario
        <input type="text" name="usuario" class="input-medium search-query" >
        Perfil
        <select name="perfil">
            <option value="">Seleccione...</option>
            <option value="Administrador">Administrador</option>
            <option value="Secretaria">Secretaria</option>
        </select>
        
        <label class="radio inline">
            <input TYPE="radio" VALUE="true" NAME="destado" checked>Activos 
        </label>
        <label class="radio inline" >
            <input TYPE="radio" VALUE="false" NAME="destado" >Inactivos 
        </label>
        <button type="submit" class="btn btn-inverse" name="buscar">Buscar</button>
    </form>
    
    <div style="background: white; padding: 5px; border-radius: 5px; border: 1px #ccc solid; box-shadow: 1px 0px 5px 1px #cccccc;">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center" >Usuario</th>
                    <th class="text-center">Perfil</th>
                    <th class="text-center">Estado</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->datos as $d) : ?>
                <tr>
                    <td><?php echo $d->nombre_usuario; ?></td>
                    <td><?php echo $this->escape($d->perfil); ?></td>
                    <td><?php echo $this->escape($d->estado); ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                              Opciones <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu" role="menu">
                              <li><a href="#">Editar</a></li>
                              <li><a href="#">Eliminar</a></li>
                              <li><a href="#">Actualizar</a></li>
                              <li class="divider"></li>
                              <li><a href="#">Acción #4</a></li>
                            </ul>
                          </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div align="right">
        <a class="btn btn-danger" href="<?php echo $this->url(array('module'=>'default','controller'=>'usuarios','action'=>'insertar')); ?>">Ingresar nuevo usuario</a>
        </div>
        
        <p class="text-center">
    <button class="btn btn-default" data-toggle="modal" data-target="#loginModal">Login</button>
</p>

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Login</h4>
            </div>

            <div class="modal-body">
                <!-- The form is placed inside the body of modal -->
                <form id="loginForm" method="post" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-xs-3 control-label">Username</label>
                        <div class="col-xs-5">
                            <input type="text" class="form-control" name="username" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label">Password</label>
                        <div class="col-xs-5">
                            <input type="password" class="form-control" name="password" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-5 col-xs-offset-3">
                            <button type="submit" class="btn btn-primary">Login</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#loginForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            username: {
                validators: {
                    notEmpty: {
                        message: 'The username is required'
                    }
                }
            },
            password: {
                validators: {
                    notEmpty: {
                        message: 'The password is required'
                    }
                }
            }
        }
    });
});
$(document).ready(function() {
    $('#loginForm').formValidation({
        message: 'This value is not valid',
        excluded: [':disabled'],
        
    });
});
$('#loginModal').on('shown.bs.modal', function() {
    $('#loginForm').formValidation('resetForm', true);
});
</script>
    </div>
    
</aside>