<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">ESTADO DE CR&Eacute;DITO</h4></div>
    </div>
    <div class="panel panel-body">
        <form class="form-horizontal" id="insertEstado" method="post">
            <div class="panel panel-body">
                <?php //echo $this->anadir->getElement('tipo');?>
            </div>
        </form>
    </div>
</aside>