<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">ESTADO DE CR&Eacute;DITO</h4></div>
    </div>
    <div class="panel panel-body">
        <form class="form-inline" id="insertEstado" method="post">
            <label>Nombre del Estado: </label>
            <div class="form-group">
                <?php echo $this->anadir->getElement('tipo');?>
            </div>
            <label>Descripci&oacute;n: </label>
            <div class="form-group">
                <?php echo $this->anadir->getElement('descripcion');?>
            </div>
            <div class="form-group">
                <?php echo $this->anadir->getElement('insertar');?>
            </div>
        </form>
    </div>
    <div class="panel panel-body">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Descripci&oacute;n</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->listaEstado as $d) : ?>
                <tr>
                    <td><?php echo $d->nombre_estado_credito; ?></td>
                    <td><?php echo $this->escape($d->descripcion_estado_credito); ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                              Opciones <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu" role="menu">
                              <li><a href="#">Editar</a></li>
                              <li><a href="#">Eliminar</a></li>
                            </ul>
                          </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</aside>
<script>
    $(document).ready(function(){
        $('.dropdown-toggle').dropdown();});
</script>