<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">MODALIDAD DE CRÉDITO</h4></div>
    </div>
    <form class="form-inline form-group">                    
        <label>Filtrar por: </label>
        <div class="btn-group">
            <span class="label label-primary" style="padding: 5px;">Modalidad</span>
        </div>
        <div class="form-group">
            <select name="modalidad" class="form-control">
                <option value="">Seleccione...</option>
                <?php foreach ($this->mostrarmodalidad as $mod) : ?>
                <option value="<?php echo $mod->cod_modalidad_credito; ?>">
                    <?php echo $mod->nombre_modalidad_credito;?>
                </option>
                <?php endforeach;?>
            </select>
        </div>
    </form>
    <div style="text-align: right" class="form-group">
        <button type="button" class="btn btn-danger" name="other">Añadir otro filtro</button>
        <input type="button" value="Buscar" class="btn btn-danger"/>
    </div>
    <div style="background: white; padding: 5px; border-radius: 5px; border: 1px #ccc solid; box-shadow: 1px 0px 5px 1px #cccccc;">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Modalidad</th>
                    <th class="text-center">Descripción</th>
                    <th><?php echo $this->mostrar; ?></th>
                </tr>
            </thead>
            
            <tbody>
                <?php foreach ($this->mostrarmodalidad as $mod) : ?>
                <tr>
                    <td><?php echo $this->escape($mod->nombre_modalidad_credito);?></td>
                    <td><?php echo $this->escape($mod->descripcion_modalidad); ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                              Opciones <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <?php $idmod=$mod->cod_modalidad_credito; ?>
                                <li><a data-toggle="modal" href="#<?php echo $idmod; ?>">Ver</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Editar</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Eliminar</a></li>
                            </ul>
                            <div id="<?php echo $idmod; ?>" class="modal fade">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title">Modalidad de crédito</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Do you want to save changes you made to document before closing?</p>
                                            <p class="text-warning"><small>If you don't save, your changes will be lost.</small></p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="button" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
        <p class="text-right">
            <button class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Ingresar modalidad de crédito</button>
        </p>
        <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
            
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Nueva modalidad de crédito</h4>
                    </div>
                    <div class="modal-body">
                        <!-- The form is placed inside the body of modal -->
                        <?php include './addmodalidad.phtml'; ?>
                    </div>
                    
                </div>
            </div>
        </div>
        
        
    </div>

</aside>
<script>
    $(document).ready(function(){
        $('.dropdown-toggle').dropdown();});
</script>