<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">MODALIDAD DE CRÉDITO</h4></div>
    </div>
    <div class="panel panel-body">
        <form class="form-inline form-group">                    
            <label>Filtrar por: </label>
            <div class="btn-group">
                <span class="label label-primary" style="padding: 5px;">Modalidad</span>
            </div>
            <div class="form-group">
                <select name="modalidad" class="form-control">
                    <option value="">Seleccione...</option>
                    <?php foreach ($this->mostrarmodalidad as $mod) : ?>
                    <option value="<?php echo $mod->cod_modalidad_credito; ?>">
                        <?php echo $mod->nombre_modalidad_credito;?>
                    </option>
                    <?php endforeach;?>
                </select>
            </div>
            <div style="text-align: right" class="form-group">
                <input type="button" value="Buscar" class="btn btn-danger"/>
            </div>
        </form>
    </div>
    
    <div style="box-shadow: 1px 0px 5px 1px #cccccc;" class="panel panel-body">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Modalidad</th>
                    <th class="text-center">Descripción</th>
                    <th></th>
                </tr>
            </thead>
            
            <tbody>
                <?php foreach ($this->mostrarmodalidad as $mod) : ?>
                <tr>
                    <?php $idmod=$mod->cod_modalidad_credito; ?>
                    <td id="tdd<?php echo $idmod;?>" value="<?php echo $this->escape($mod->nombre_modalidad_credito);?>"><?php echo $this->escape($mod->nombre_modalidad_credito);?></td>
                    <td id='td<?php echo $idmod; ?>' value="<?php echo $this->escape($mod->descripcion_modalidad); ?>"><?php echo substr($this->escape($mod->descripcion_modalidad),0,20)."..."; ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                              Opciones <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a data-toggle="modal" name='<?php echo $idmod; ?>' href="#verModal">Ver</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Editar</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Eliminar</a></li>
                            </ul>
                            <div id="verModal" class="modal fade">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title"><strong>Modalidad de crédito</strong></h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="well">
                                                <h5><strong><div id="muestranom" align="left"></div></strong></h5>
                                                <p id='texto' align="justify" ></p>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                                            <!--<button type="button" class="btn btn-primary">Save changes</button>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
        <p class="text-right" style="margin-top: 20px;">
            <button class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Ingresar modalidad de crédito</button>
        </p>
        <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
            
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Nueva modalidad de crédito</h4>
                    </div>
                    <div class="modal-body">
                        <!-- The form is placed inside the body of modal -->
                        <form id="loginForm" method="post" class="form-horizontal">
                            <div class="form-group">
                                <?php echo $this->add->getElement('cod_modalidad_credito'); ?>
                                <label class="col-xs-4 control-label">Nombre de modalidad</label>
                                <div class="col-xs-7">
                                    <?php echo $this->add->getElement('nombre_modalidad_credito'); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-xs-4 control-label">Descripción</label>
                                <div class="col-xs-7">
                                    <?php echo $this->add->getElement('descripcion_modalidad'); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-5 col-xs-offset-3">
                                    <?php echo $this->add->getElement('submitmodalidad'); ?>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </form>
                        <?php //include './addmodalidad.phtml'; ?>
                    </div>
                    
                </div>
            </div>
        </div>
        
        
    </div>

</aside>
<script>
    $(document).ready(function(){
        $('.dropdown-toggle').dropdown();
            /*$('td:nth-child(2)').each(function(){
            if ($(this).text().length > 20)
                $(this).text($(this).text().substring(0,20));
        });*/
        $('a').click(function(){
            $('p[id=texto]').text($('td[id=td'+$(this).attr('name')+']').attr('value'));
            $('div[id=muestranom]').text($('td[id=tdd'+$(this).attr('name')+']').attr('value'));
        });
    });
</script>